import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SideNav from "@/components/SideNav";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideNav />
        <main className="min-h-screen pl-72 pr-12 py-12 bg-gray-50">
          {children}
        </main>
      </body>
    </html>
  );
}
